---
- hosts: "{{ hosts | default('etcd-nodes') }}"
  gather_facts: yes
  tasks:

    - debug:
        var: 'vars'
      run_once: true
        

    # - name: debug current_hosts 1
    #   delegate_to: localhost
    #   delegate_facts: yes
    #   debug:
    #     var: current_hosts

    # - name: append current_hosts
    #   delegate_to: localhost
    #   delegate_facts: yes
    #   set_fact:
    #     current_hosts: "{{ current_hosts }} + [ {{ inventory_hostname }} ]"

    # - name: debug current_hosts 2
    #   delegate_to: localhost
    #   delegate_facts: yes
    #   debug:
    #     var: current_hosts