- name: 'ensure directory {{binary_dir}} exists'
  file:
    path:  '{{binary_dir}}'
    state: 'directory'

- name: 'add {{binary_dir}} to PATH permanently'
  lineinfile:
      path: '{{ansible_env.HOME}}/.profile'
      line: 'PATH="$PATH:{{binary_dir}}" # ansible'

- set_fact:
    binary_dir: '{{binary_dir}}'