- name: 'ensure directory {{binary_dir}} exists'
  file:
    path:  '{{binary_dir}}'
    state: 'directory'

- name: 'add {{binary_dir}} to PATH permanently'
  lineinfile:
      path: /etc/profile
      line: 'PATH="$PATH:{{binary_dir}}"'

