
- name: 'create {{service_name}} systemd service'
  template: 
    src:  '{{playbook_dir}}/src/systemd/{{service_name}}.service.j2'
    dest: '/etc/systemd/system/{{service_name}}.service'
    mode: 644

- name: enable systemd service
  systemd:
    daemon_reload: yes
    name: '{{service_name}}'
    enabled: yes
    state: restarted
    masked: no

