---
- name: install cfssl binaries on remote host
  become: yes
  when: cfssl_installed_remotely|default(False) == False
  block: 

    - name: download cloudflare binaries remotely
      get_url:
        url: 'https://pkg.cfssl.org/R1.2/{{cflss_binary_name}}_linux-amd64'
        dest: '/opt/bin/{{cflss_binary_name}}'
        mode: ugo+x
      loop: 
        - cfssl
        - cfssljson
      loop_control: {loop_var: cflss_binary_name}
        
    - name: keep from running multiple times
      set_fact: 
        cfssl_installed_remotely: True
