---
- name: install cfssl binaries on remote host
  become: yes
  when: cfssl_installed_remotely|default(False) == False
  block: 

    - name: download cloudflare binaries remotely
      get_url:
        url: 'https://storage.googleapis.com/kubernetes-the-hard-way/cfssl/1.4.1/linux/{{cflss_binary_name}}'
        dest: '/usr/local/bin/{{cflss_binary_name}}'
        mode: ugo+x
      loop: 
        - cfssl
        - cfssljson
      loop_control: {loop_var: cflss_binary_name}
        
    - name: keep from running multiple times
      set_fact: 
        cfssl_installed_remotely: True
