

- name: guess k8s worker node name
  set_fact:
    etcd_node_name: '{{ k8s_worker_node_name | default(node_name) | default("k8s-worker-" + (1+ansible_play_batch.index(inventory_hostname))|string) }}'
      


- name: 
  block:
    - name: 'generate kube config for {{item}}'
      include_role:
        include_role:
          name: kubeconfig
          vars:
            client_name: '{{item}}'            

    - name: download kube-apiserver binary distribution
      get_url:
        url: 'https://storage.googleapis.com/kubernetes-release/release/v1.15.3/bin/linux/amd64/{{item}}'
        dest: /usr/local/bin
        mode: ugo+x

    - name: create etcd systemd service
      template: 
        src:  '{{role_path}}/templates/{{item}}.service.j2'
        dest: '/etc/systemd/system/{{item}}.service'
        mode: 644

    - name: enable systemd service
      systemd:
        daemon_reload: yes
        name: '{{item}}'
        enabled: yes
        state: restarted
        masked: no

  with_items:
    - kube-proxy
    - worker

