- file:
    path: /opt/bin
    state: directory

- name: download kubectl binary distribution
  get_url:
    url: 'https://storage.googleapis.com/kubernetes-release/release/v1.15.3/bin/linux/amd64/kubectl'
    dest: /opt/bin
    mode: ugo+x
