
- name: download kubectl binary distribution
  become: yes
  get_url:
    url: 'https://storage.googleapis.com/kubernetes-release/release/v1.15.3/bin/linux/amd64/kubectl'
    dest: /usr/local/bin
    mode: ugo+x
