- name: "setting ip addresses of all hosts to each node's /etc/hosts"
  become: yes
  lineinfile:
    path: /etc/hosts
    line: '{{hostvars[item].internal_ip_address|default(hostvars[item].ansible_default_ipv4.address)|default(hostvars[item].ansible_all_ipv4_addresses[0])}} {{item}}'
  with_items: '{{ansible_play_hosts}}'