# if destination_hosts is defined, parse it as as host list and add them to /etc/hosts
# otherwise just add currently run hosts to /etc/hosts
- become: yes
  block:
    - when: 'destination_hosts|default("")|string|length>0'
      lineinfile: &lineinfile_config
        path: /etc/hosts
        line: '{{hostvars[item].internal_ip_address
          |default(hostvars[item].ansible_default_ipv4.address)
          |default(hostvars[item].ansible_all_ipv4_addresses[0])
          |default(hostvars[item].inventory_hostname)}} {{hostvars[item].internal_hostname
          |default(item)}} # ansible'
      with_inventory_hostnames:
        - '{{destination_hosts}}'
    - when: 'destination_hosts|default("")|string|length==0'
      lineinfile: *lineinfile_config
      with_items: '{{ansible_play_hosts}}'