- stat:
    path: '{{ceph_osd_device_data_file}}'
  register: stat_result

- when: not stat_result.stat.exists
  shell: >-
    truncate -s '{{ceph_osd_device_size}}' '{{ceph_osd_device_data_file}}'

- set_fact:
    this_role_path: '{{role_path}}'

- include_role:
    name: systemd-service
  vars:
    service_name: ceph-osd-device-attach
    service_file_template: '{{this_role_path}}/templates/ceph-osd-device-attach.service.j2'